//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace experiment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDetail
    {
        public int ID { get; set; }
        public string SID { get; set; }
        public string Details { get; set; }
        public string Timestamp { get; set; }
        public string Queries { get; set; }
    
        public virtual LogData LogData { get; set; }
    }
}
