//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace experiment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public LogData()
        {
            this.LogDetails = new HashSet<LogDetail>();
        }
    
        public string SID { get; set; }
        public string UID { get; set; }
        public string IP { get; set; }
    
        public virtual ICollection<LogDetail> LogDetails { get; set; }
    }
}
